### ISSUE TITLE
Schematic and PCB

### ISSUE THREAD

**Issue by sabas1080** [amilkovich/snes-rd#1]
Hi

Great project, i can made schematic and PCB, but if you can draw diagram on a piece of paper , I can do

Thanks :D

**Comment by amilkovich** [comment]
Please email me. You can find my address in LICENSE file.

**Comment by sabas1080** [comment]
Done

**Comment by Fordi** [comment]
Any data here yet?

**Comment by dtomcat** [comment]
I've added a schematic.  I just need help compiling.  Can anyone help me with compiling and loading into Teensy?    schematic is in closed issues.

**Comment by Lutz89** [comment]
So you still need help with the Firmware? Ich can send you some Details or the compiled Hex File.

**Comment by dtomcat** [comment]
I got it figured out. Had to download an older version of one of the files.  Works now.  Thanks!

**Comment by bernardo-amaral** [comment]
Hi guys, any progress with the schematic? I loved this project!!!

**Comment by dtomcat** [comment]
I have completed the schematic awhile ago... Just looked at the closed issues.

**Comment by viniciuspaes** [comment]
The original author is Andrew Milkovich and he passed away in 12/March/2017.
Rest in Peace

**Comment by dtomcat** [comment]
Sad to hear
